'use client';

import { useState } from 'react';
import type { ArtifactProvenance } from '@keviq/domain-types';

/** Map internal provider names to human-friendly labels. */
function humanProvider(provider: string | null): string {
  if (!provider) return 'AI model';
  const MAP: Record<string, string> = {
    claude_code_cli: 'Claude (via local bridge)',
    openai: 'OpenAI',
    anthropic: 'Anthropic',
  };
  return MAP[provider] ?? provider;
}

function buildHeadline(prov: ArtifactProvenance): string {
  if (prov.model_name_concrete) {
    const provider = humanProvider(prov.model_provider);
    const model = prov.model_name_concrete;
    return `Generated by ${model} · ${provider}`;
  }
  if (prov.tool_name) {
    const version = prov.tool_version ? ` ${prov.tool_version}` : '';
    return `Created using ${prov.tool_name}${version}`;
  }
  return 'Provenance recorded';
}

function countHashFields(prov: ArtifactProvenance): number {
  return [prov.system_prompt_hash, prov.run_config_hash, prov.tool_config_hash].filter(Boolean).length;
}

export function ProvenanceTrustCard({
  provenance,
  isLoading,
  isError,
}: {
  provenance: ArtifactProvenance | null | undefined;
  isLoading: boolean;
  isError: boolean;
}) {
  const [expanded, setExpanded] = useState(false);

  if (isLoading) return <p style={{ color: '#9ca3af', fontSize: 13 }}>Loading provenance...</p>;
  if (isError) return <p style={{ color: '#b91c1c', fontSize: 13 }}>Failed to load provenance.</p>;
  if (!provenance) return <p style={{ color: '#9ca3af', fontSize: 13 }}>No provenance record available.</p>;

  const headline = buildHeadline(provenance);
  const hashDepth = countHashFields(provenance);

  return (
    <div style={{ backgroundColor: '#f8fafc', borderRadius: 8, border: '1px solid #e2e8f0', padding: 16 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap', marginBottom: 4 }}>
        <span style={{ fontSize: 14, fontWeight: 600, color: '#1e293b' }}>{headline}</span>
        {hashDepth > 0 && (
          <span style={{
            fontSize: 11, padding: '2px 6px',
            backgroundColor: '#e0f2fe', color: '#0369a1',
            borderRadius: 4, fontWeight: 600,
          }}>
            {hashDepth} hash{hashDepth > 1 ? 'es' : ''} verified
          </span>
        )}
      </div>

      {provenance.model_provider && (
        <p style={{ fontSize: 13, color: '#64748b', margin: '0 0 6px' }}>
          Provider: {humanProvider(provenance.model_provider)}
          {provenance.model_temperature != null ? ` · temp ${provenance.model_temperature}` : ''}
          {provenance.model_max_tokens != null ? ` · max ${provenance.model_max_tokens} tokens` : ''}
        </p>
      )}

      <button
        type="button"
        onClick={() => setExpanded((v) => !v)}
        style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: 12, color: '#6b7280', padding: 0 }}
      >
        {expanded ? '▾ Hide raw details' : '▸ Show raw details'}
      </button>

      {expanded && (
        <dl style={{ display: 'grid', gridTemplateColumns: 'max-content 1fr', gap: '4px 12px', margin: '8px 0 0', fontSize: 12 }}>
          {provenance.model_version_concrete && (
            <>
              <dt style={{ color: '#94a3b8' }}>Model version</dt>
              <dd style={{ margin: 0 }}>{provenance.model_version_concrete}</dd>
            </>
          )}
          {provenance.system_prompt_hash && (
            <>
              <dt style={{ color: '#94a3b8' }}>Prompt hash</dt>
              <dd style={{ margin: 0, fontFamily: 'monospace', wordBreak: 'break-all' }}>{provenance.system_prompt_hash}</dd>
            </>
          )}
          {provenance.run_config_hash && (
            <>
              <dt style={{ color: '#94a3b8' }}>Config hash</dt>
              <dd style={{ margin: 0, fontFamily: 'monospace', wordBreak: 'break-all' }}>{provenance.run_config_hash}</dd>
            </>
          )}
          {provenance.tool_config_hash && (
            <>
              <dt style={{ color: '#94a3b8' }}>Tool config hash</dt>
              <dd style={{ margin: 0, fontFamily: 'monospace', wordBreak: 'break-all' }}>{provenance.tool_config_hash}</dd>
            </>
          )}
          {provenance.tool_name && (
            <>
              <dt style={{ color: '#94a3b8' }}>Tool</dt>
              <dd style={{ margin: 0 }}>{provenance.tool_name}{provenance.tool_version ? ` v${provenance.tool_version}` : ''}</dd>
            </>
          )}
          {provenance.input_snapshot && Object.keys(provenance.input_snapshot).length > 0 && (
            <>
              <dt style={{ color: '#94a3b8' }}>Input snapshot</dt>
              <dd style={{ margin: 0 }}>
                <pre style={{ margin: 0, fontSize: 11, whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>
                  {JSON.stringify(provenance.input_snapshot, null, 2)}
                </pre>
              </dd>
            </>
          )}
        </dl>
      )}
    </div>
  );
}
