export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  ONBOARDING: '/onboarding',
  ROOT: '/',
  WORKSPACE: '/workspaces/[workspaceId]',
  TASKS: '/workspaces/[workspaceId]/tasks',
  TASK_DETAIL: '/workspaces/[workspaceId]/tasks/[taskId]',
  TASK_NEW: '/workspaces/[workspaceId]/tasks/new',
  RUN_DETAIL: '/workspaces/[workspaceId]/runs/[runId]',
  ARTIFACTS: '/workspaces/[workspaceId]/artifacts',
  ARTIFACT_DETAIL: '/workspaces/[workspaceId]/artifacts/[artifactId]',
  SETTINGS_POLICIES: '/workspaces/[workspaceId]/settings/policies',
  SETTINGS_SECRETS: '/workspaces/[workspaceId]/settings/secrets',
  SETTINGS_INTEGRATIONS: '/workspaces/[workspaceId]/settings/integrations',
  ACTIVITY: '/workspaces/[workspaceId]/activity',
  NOTIFICATIONS: '/workspaces/[workspaceId]/notifications',
  APPROVALS: '/workspaces/[workspaceId]/approvals',
  APPROVAL_DETAIL: '/workspaces/[workspaceId]/approvals/[approvalId]',
} as const;
